version: '3.8'

services:
  bot:
    build:
      context: ./bot
    restart: always
    env_file: ./bot/.env
    volumes:
      - ./bot:/app
      - ./backend:/app/backend
    dns:
      - 127.0.0.11
      - 8.8.8.8
    command: >
      bash -c "pip install -r requirements.txt &&
               python main_production.py"
    environment:
      - PYTHONUNBUFFERED=1
      - USE_SIMPLE_STORAGE=false
      - BACKEND_URL=http://backend:8000
    networks:
      - vpn_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "8001:8000"
    env_file: .env
    volumes:
      - ./backend:/app
    dns:
      - 127.0.0.11
      - 8.8.8.8
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - DATABASE_URL=postgresql+asyncpg://vpn_user:vpn_password@db:5432/vpn_db
    networks:
      - vpn_network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - vpn_network

networks:
  vpn_network:
    driver: bridge

volumes:
  postgres_data:
    name: vpn-bezlagov_postgres_data
    external: true 